@base=http://localhost:4000

###
# @name auth
POST {{base}}/auth
Content-Type: application/json

{"username": "admin", "password": "admin"}

###
@token={{auth.response.body.token}}

###
# @name profile
GET {{base}}/profile
Authorization: Bearer {{token}}