@base=http://localhost:4000
@id=98588ec5-093f-4097-b901-6bcf5e2ef68f

### show all users
GET {{base}}/users

### show user
GET {{base}}/users/{{id}}

### create user
POST {{base}}/users
Content-Type: application/json

{
    "name": "Brasilio Thomazo",
    "phone": "+551191234567",
    "email": "brasilio.thomazo@gmail.com",
    "username": "brasilio",
    "password": "abc123",
    "password_confirmation": "abc123"
}