@base=http://localhost:4000
@id=a89ce7ba-bd53-40cf-9021-71417e578df2

### show all users
GET {{base}}/users

### show user
GET {{base}}/users/{{id}}

### create user
POST {{base}}/users
Content-Type: application/json

{
    "name": "Brasilio Thomazo",
    "phone": "+551191234567",
    "email": "brasilio.thomazo@gmail.com",
    "username": "brasilio",
    "password": "abc123",
    "password_confirmation": "abc123"
}