services:
  migrate:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: migrate
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/cash
    command: ["sh", "-c", "api migrate && api seed"]
    depends_on:
      - db
  api-1:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api-1
    volumes:
      - ./private.pem:/app/private.pem
      - ./public.pem:/app/public.pem
    environment:
      - JWT_PRIVATE_KEY_PATH=/app/private.pem
      - JWT_PUBLIC_KEY_PATH=/app/public.pem
      - DATABASE_URL=postgres://postgres:postgres@db/cash
    depends_on:
      - db

  api-2:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api-2
    volumes:
      - ./private.pem:/app/private.pem
      - ./public.pem:/app/public.pem
    environment:
      - JWT_PRIVATE_KEY_PATH=/app/private.pem
      - JWT_PUBLIC_KEY_PATH=/app/public.pem
      - DATABASE_URL=postgres://postgres:postgres@db/cash
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cash
  
  haproxy:
    build:
      context: haproxy
      dockerfile: Dockerfile
    container_name: haproxy
    ports:
      - "80:80"
    environment:
      - BACKEND_1_HOST=api-1
      - BACKEND_2_HOST=api-2
      - BACKEND_1_PORT=4000
      - BACKEND_2_PORT=4000
    depends_on:
      - api-1
      - api-2
